FROM node:18.14.2-alpine3.16 as building

RUN apk add --no-cache git=2.36.6-r0

WORKDIR /app

COPY package.json yarn.lock chronix.config.ts .env ./
COPY jest* ./
COPY ./tsconfig*.json ./

RUN yarn install --frozen-lockfile --non-interactive && yarn cache clean
COPY ./src ./src
RUN yarn typechain

CMD ["yarn", "test:e2e:docker"]
