version: '3.9'

networks:
  devnet:
    name: ${DOCKER_NETWORK_NAME}
    external: true

services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    networks:
      - devnet
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data

  keys_api:
    build: ./
    platform: linux/amd64
    restart: always
    networks:
      - devnet
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - CORS_WHITELIST_REGEXP=${CORS_WHITELIST_REGEXP}
      - GLOBAL_THROTTLE_TTL=${GLOBAL_THROTTLE_TTL}
      - GLOBAL_THROTTLE_LIMIT=${GLOBAL_THROTTLE_LIMIT}
      - GLOBAL_CACHE_TTL=${GLOBAL_CACHE_TTL}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOG_FORMAT=${LOG_FORMAT}
      - PROVIDERS_URLS=${PROVIDERS_URLS}
      - CL_API_URLS=${CL_API_URLS}
      - CHAIN_ID=${CHAIN_ID}
      - DB_NAME=${DB_NAME}
      - DB_PORT=5432
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - JOB_INTERVAL_REGISTRY=${JOB_INTERVAL_REGISTRY}
      - VALIDATOR_REGISTRY_ENABLE=${VALIDATOR_REGISTRY_ENABLE}
      - JOB_INTERVAL_VALIDATORS_REGISTRY=${JOB_INTERVAL_VALIDATORS_REGISTRY}
      - LIDO_LOCATOR_DEVNET_ADDRESS=${LIDO_LOCATOR_DEVNET_ADDRESS}
      - CURATED_MODULE_DEVNET_ADDRESS=${CURATED_MODULE_DEVNET_ADDRESS}
      - CSM_MODULE_DEVNET_ADDRESS=${CSM_MODULE_DEVNET_ADDRESS}
      - STAKING_ROUTER_DEVNET_ADDRESS=${STAKING_ROUTER_DEVNET_ADDRESS}
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - db

volumes:
  pgdata:
