global:
  scrape_interval: 5s
scrape_configs:
  - job_name: 'keys-api'
    static_configs:
      - targets: ['docker.for.mac.host.internal:3000']
remote_write:
  - url: https://localhost/api/v1/write

rule_files:
  - 'alerts/keys-api-outdated-keys.empty-db.rule.yml'
  - 'alerts/keys-api-outdated-keys.non-empty-db.rule.yml'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['docker.for.mac.host.internal:9093']
